version: 2

sources:
  - name: raw_data
    description: "Raw data from the taxi rides dataset"
    database: taxi_rides_ny # Project ID
    schema: prod # Dataset name
    tables:
      - name: yellow_tripdata
      - name: green_tripdata